import test from 'node:test';import assert from 'node:assert/strict';
import {CanvasTileMap,visibleVisualTiles,drawVisualTiles} from '../src/canvas-tile-map.js';
import {mercatorProject,mercatorUnproject} from '../src/mercator-view.js';
function setup(){const calls=[],context={save(){},restore(){},clearRect(){},fillRect(){},setTransform(){},drawImage(...args){calls.push(args);}},container={clientWidth:390,clientHeight:844,replaceChildren(){},append(){}};const previous={document:globalThis.document,devicePixelRatio:globalThis.devicePixelRatio};globalThis.document={createElement:()=>({style:{},setAttribute(){},getContext:()=>context})};globalThis.devicePixelRatio=1;const image={},layer={stats:{},get:()=>image,ensure:async()=>{},dispose(){this.disposed=true;}};return{calls,context,container,layer,restore(){Object.assign(globalThis,previous);}};}
test('visual LOD stays bounded across world, giant-hole and portrait views',()=>{for(const center of [[0,0],[179.99,60],[-179.99,-60],[30,84.94]])for(const zoom of [0,2,9,12,14,17,19])for(const size of [[390,844],[1920,1080],[5000,5000]]){const tiles=visibleVisualTiles(center,zoom,...size);assert.ok(tiles.length<=16);assert.equal(new Set(tiles.map(t=>`${t.z}/${t.x}/${t.y}`)).size,tiles.length);for(const t of tiles){assert.ok(t.z<=14&&t.x>=0&&t.x<2**t.z&&t.y>=0&&t.y<2**t.z);}}});
test('true Mercator preserves high-latitude arena rows and round trips',()=>{const a=mercatorProject([30,84.9]),b=mercatorProject([30,84.94]);assert.ok(b[1]<a[1]);const p=mercatorUnproject(b);assert.ok(Math.abs(p[1]-84.94)<1e-10);});
test('camera motion redraws cached tile images even if tile membership is unchanged',async()=>{const f=setup();try{const map=new CanvasTileMap({container:f.container,center:[30,60],zoom:17,source:{},metadata:{attribution:'OSM'},layerFactory:()=>f.layer});await map.ready;const signature=map.requested,draws=map.stats.frames,old=f.calls.at(-1)[1];map.jumpTo({center:[30.00001,60],zoom:17});assert.equal(map.requested,signature);assert.ok(map.stats.frames>draws);assert.notEqual(f.calls.at(-1)[1],old);map.remove();assert.equal(f.layer.disposed,true);}finally{f.restore();}});
test('Canvas project agrees with tile placements including world seam',async()=>{const f=setup();try{const map=new CanvasTileMap({container:f.container,center:[179.99,60],zoom:17,source:{},metadata:{attribution:'OSM'},layerFactory:()=>f.layer});await map.ready;assert.ok(Math.abs(map.project([-179.999,60]).x-map.width/2)<3000);assert.deepEqual(map.project([179.99,60]),{x:195,y:422});map.remove();}finally{f.restore();}});
test('a missing background tile is counted, never represented by invented map data',()=>{const f=setup();try{const r=drawVisualTiles(f.context,{get:()=>null},[{z:14,x:9573,y:4757}],{center:[30,60],zoom:14,width:390,height:844});assert.equal(r.missing,1);assert.equal(r.drawn,0);assert.equal(f.calls.length,0);}finally{f.restore();}});

import {canvasPixelRatio,MAX_CANVAS_PIXELS} from '../src/canvas-budget.js';
test('backing stores cap device ratio and total pixels on phones and huge monitors',()=>{for(const [w,h] of [[390,844],[1920,1080],[7680,4320]])for(const ratio of [1,2,3,4]){const d=canvasPixelRatio(w,h,ratio);assert.ok(d<=2&&d<=ratio);assert.ok(Math.floor(w*d)*Math.floor(h*d)<=MAX_CANVAS_PIXELS);assert.ok(canvasPixelRatio(w,h,ratio,'low')<=1);}});
