import test from 'node:test';import assert from 'node:assert/strict';import 'fake-indexeddb/auto';
import {GeoJSONVT} from '@maplibre/geojson-vt';import {fromGeojsonVt} from '@maplibre/vt-pbf';
import {reconstructWaterBoundary,waterBoundaryTiles,rasterizeWaterRegion} from '../src/water-boundary.js';
import {localToLonLat} from '../src/geometry.js';import {StreamStore,STREAM_DB_NAME} from '../src/stream-store.js';
import {StreamingGame} from '../src/streaming-game.js';import {ConsumptionMask,maskChunksForBounds,rasterizeCoverageChunk,countMaskBits} from '../src/consumption-mask.js';
import {landGoal,createStreamRun,streamProgress} from '../src/streaming-state.js';
const manifest={id:'land-fixture',center:[0,0],projectionLatitude:0},rect=(a,b,c,d)=>[[a,b],[c,b],[c,d],[a,d],[a,b]],building=[[rect(-100,-30,100,30)]];
async function boundaryFor(water=[],m=manifest){const features=water.map(r=>({type:'Feature',properties:{class:'river'},geometry:{type:'Polygon',coordinates:[r.map(p=>localToLonLat(p,m.center,m.projectionLatitude))]}})),index=new GeoJSONVT({type:'FeatureCollection',features},{maxZoom:14,indexMaxZoom:14,indexMaxPoints:0,extent:4096,buffer:64,tolerance:0}),tiles=waterBoundaryTiles(m).map(c=>{const b=fromGeojsonVt({water:index.getTile(14,c.x,c.y)||{features:[]}},{extent:4096});return{...c,sourceKey:'fixture',buffer:b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}});return{...await reconstructWaterBoundary(tiles,m),envelopeId:m.id};}
const riverPromise=boundaryFor([rect(-10,-3000,10,3000)]);
function fixture(boundary,store=new StreamStore(),mode='parts'){let prepared=0,sourceCalls=0;const game=new StreamingGame({sector:manifest,store,mode,goalChoice:'100',boundaryFactory:()=>({stats:{},prepare:async()=>{sourceCalls++;return boundary;},rasterizeRegion:(b,id)=>rasterizeWaterRegion(b,id,manifest),dispose(){}}),displayFactory:()=>({changed(){},dispose(){}}),streamFactory:({mask})=>({source:{stats:{}},metadata:{},prepare:async()=>{prepared++;for(const key of maskChunksForBounds([-1500,-1500,1500,1500]))mask.ingestCoverage(key,rasterizeCoverageChunk(key,building));},covers:()=>true,update:async()=>{},dispose(){}})});return{game,store,get sourceCalls(){return sourceCalls},get prepared(){return prepared}};}
const fresh=async()=>{await new Promise((r,j)=>{const q=indexedDB.deleteDatabase(STREAM_DB_NAME);q.onsuccess=r;q.onerror=()=>j(q.error)});return new StreamStore();};
test('active mask clips Parts and Whole, excludes neighbor and rejects saved cells outside frozen land',()=>{const mask=new ConsumptionMask(),key='2,2',left=rasterizeCoverageChunk(key,[[rect(-200,-200,0,200)]]),all=rasterizeCoverageChunk(key,building);mask.setActiveRegion([[key,left]]);mask.ingestCoverage(key,all);const result=mask.consumeBuildingChunks([[key,all]]);assert.equal(result.areaM2,6000);assert.equal(mask.consumeCircle([50,0],200).areaM2,0);assert.throws(()=>mask.restoreConsumed([[key,all]]),/active land/);assert.equal(mask.consumedAreaM2,6000);assert.throws(()=>mask.consumeBuildingChunks([[key,new Uint8Array(8192)],[key,new Uint8Array(8192)]]));});
test('goals are explicit choices and scale to nonzero small-region ownership',()=>{assert.equal(landGoal(9000000),100000);assert.equal(landGoal(50000),1000);assert.equal(landGoal(200,'100000'),200);assert.equal(landGoal(4),4);assert.throws(()=>landGoal(0));assert.equal(streamProgress(100,1000).progress,10);assert.throws(()=>createStreamRun({...manifest,boundaryId:'b',regionId:'r',scoreAreaM2:0}));});
test('water tap freezes boundary and returns selectable geometry without loading any buildings',async()=>{const q=fixture(await riverPromise,await fresh());await assert.rejects(q.game.prepare([0,0]),e=>e.code==='WATER_SELECTION'&&e.boundary.regions.length===2);assert.equal(q.prepared,0);assert.equal((await q.store.boundaries()).length,1);q.game.dispose();q.store.db.close();});
test('different land components use separate saves; cold reopen uses frozen water and original goal',async()=>{const boundary=await riverPromise,store=await fresh(),a=fixture(boundary,store);await a.game.prepare([-30,0]);const id=a.game.run.sectorId;a.game.tick(.1,1,[0,0]);await a.game.persist();const earned=a.game.run.consumedArea;assert.ok(earned>0);a.game.dispose();const b=fixture(boundary,store);await b.game.prepare([30,0]);assert.notEqual(b.game.run.sectorId,id);assert.equal(b.game.run.consumedArea,0);assert.equal(b.sourceCalls,0);b.game.dispose();const c=fixture(boundary,store);c.game.goalChoice='100000';await c.game.prepare([-30,0]);assert.equal(c.game.run.consumedArea,earned);assert.equal(c.game.run.goalArea,100);assert.equal(c.sourceCalls,0);c.game.dispose();store.db.close();});
test('frozen boundary insertion is transactional and never overwrites another first-open result',async()=>{const a=await riverPromise,b=await boundaryFor(),store=await fresh();const results=await Promise.allSettled([store.saveBoundary(a,manifest),store.saveBoundary(b,manifest)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected').length,1);const saved=await store.getBoundary(manifest.id);assert.equal(saved.id,results.find(r=>r.status==='fulfilled').value.id);store.db.close();});
test('cancel during saved boundary read never begins source requests or scene selection',async()=>{let resolve,calls=0;const wait=new Promise(r=>resolve=r),q=fixture(await riverPromise,{getBoundary:()=>wait});q.game.boundaryFactory=()=>{calls++;throw new Error('stale')};const pending=q.game.prepare([-30,0]);q.game.dispose();resolve(null);await assert.rejects(pending,{name:'AbortError'});assert.equal(calls,0);});
