import test from 'node:test';import assert from 'node:assert/strict';import {MapExplorer,restoredExplorerCampaign} from '../src/map-explorer.js';import {getMapCellAt} from '../src/map-cells.js';
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve}};
const classes=()=>({add(){},remove(){},toggle(){}});
function fixture(){const waits=[],chosen=[],writes=[],node={classList:classes(),replaceChildren(){},querySelectorAll(){return []},dataset:{}},a=[30,60],b=[30.3,60],picker={campaign:null,busy:false,generation:0,selectionGeneration:0,visibleCells:[getMapCellAt(a),getMapCellAt(b)],element:node,$:()=>node,map:{getZoom:()=>10,easeTo(){},remove(){}},getView:()=>({center:[30,60],zoom:10}),refresh(){},status(){},cache:{getCampaign:async()=>{const d=deferred();waits.push(d);return d.promise},putCampaign:async c=>writes.push(c)},onChoose:async x=>chosen.push(x),setBusy:MapExplorer.prototype.setBusy,selectPoint:MapExplorer.prototype.selectPoint,cancelSelection:MapExplorer.prototype.cancelSelection,hide:MapExplorer.prototype.hide};return{picker,waits,chosen,writes,a,b};}
test('cancel A then start B cannot allow A late cache result to choose a stale cell',async()=>{const q=fixture(),a=q.picker.selectPoint(q.a);assert.equal(q.waits.length,1);q.picker.cancelSelection();const b=q.picker.selectPoint(q.b);assert.equal(q.waits.length,2);q.waits[0].resolve(null);await a;assert.equal(q.chosen.length,0,'Cancelled A must not enter while B is busy');q.waits[1].resolve(null);await b;assert.deepEqual(q.chosen.map(x=>x.cell.id),[getMapCellAt(q.b).id]);assert.equal(q.writes.length,1);});
test('hiding map invalidates an outstanding selection even without a replacement tap',async()=>{const q=fixture(),a=q.picker.selectPoint(q.a);q.picker.hide();q.waits[0].resolve(null);await a;assert.equal(q.chosen.length,0);assert.equal(q.writes.length,0);});

test('the map starts with the world grid, while only explicit saved campaigns restore a restricted grid',()=>{const saved={id:'legacy-city',sectors:[]};assert.equal(restoredExplorerCampaign(null,[saved]),null);assert.equal(restoredExplorerCampaign({campaignId:'prepared-maps'},[saved]),null);assert.equal(restoredExplorerCampaign({campaignId:'legacy-city'},[saved]),saved);assert.equal(restoredExplorerCampaign({campaignId:'missing'},[saved]),null);});

test('ready-map buttons can enter a prepared arena directly without changing world grid or fetching a city',async()=>{const q=fixture();q.picker.visibleCells=[];const ready={id:'pushkin',prepared:true,center:q.a};await q.picker.selectPoint(q.a,{preparedCell:ready});assert.equal(q.chosen.length,1);assert.equal(q.chosen[0].cell,ready);assert.equal(q.picker.campaign,null);assert.equal(q.waits.length,0);assert.equal(q.writes.length,0);});

test('Escape cancels from body focus while explorer is visible, clears queued taps, and ignores hidden explorer',()=>{let cancelled=0,prevented=0,hidden=false;const q=fixture();q.picker.element.classList.contains=()=>hidden;q.picker.onCancel=()=>cancelled++;q.picker.busy=true;q.picker.pendingTap=setTimeout(()=>{throw new Error('Stale queued tap ran');},1000);const event={key:'Escape',target:{tagName:'BODY'},preventDefault(){prevented++;}};MapExplorer.prototype.handleKeyDown.call(q.picker,event);assert.equal(cancelled,1);assert.equal(q.picker.pendingTap,null);assert.equal(prevented,1);hidden=true;MapExplorer.prototype.handleKeyDown.call(q.picker,event);assert.equal(cancelled,1);});
