import test from 'node:test';import assert from 'node:assert/strict';
import {RegionDisplay} from '../src/region-display.js';import {overviewPolygon} from '../src/world-overview.js';
import {mercatorProject} from '../src/mercator-view.js';import {localToLonLat} from '../src/geometry.js';
class Path{constructor(){this.points=[];this.closes=0}moveTo(x,y){this.points.push([x,y])}lineTo(x,y){this.points.push([x,y])}closePath(){this.closes++}}
const ring=[[-500,-500],[500,-500],[500,500],[-500,500],[-500,-500]],hole=[[-50,-50],[-50,50],[50,50],[50,-50],[-50,-50]];
test('frozen land paths keep holes and share the exact tilted Mercator ground transform',()=>{const manifest={center:[179.999,60],projectionLatitude:60,region:{polygons:[[ring,hole]]},boundary:{waterPolygons:[[hole]]}},display=new RegionDisplay(manifest,()=>new Path());assert.equal(display.paths.land.closes,2);const frame={worldSize:1234567,groundScaleY:.901,offsetX:-123,offsetY:321},commands=[],c={translate:(...v)=>commands.push(['translate',...v]),scale:(...v)=>commands.push(['scale',...v])};display.transform(c,frame);const [x,y]=display.paths.land.points[0],projected=mercatorProject(localToLonLat(ring[0],manifest.center,60));projected[0]+=Math.round(display.origin[0]-projected[0]);assert.ok(Math.abs((display.origin[0]+x)*frame.worldSize+frame.offsetX-(projected[0]*frame.worldSize+frame.offsetX))<1e-7);assert.ok(Math.abs((display.origin[1]+y)*frame.worldSize*frame.groundScaleY+frame.offsetY-(projected[1]*frame.worldSize*frame.groundScaleY+frame.offsetY))<1e-7);assert.equal(commands[1][2],frame.worldSize*frame.groundScaleY);});
test('water overlay and score clip use cached paths and evenodd holes, then restore screen coordinates',()=>{const d=new RegionDisplay({center:[30,60],region:{polygons:[[ring,hole]]},boundary:{waterPolygons:[[hole]]}},()=>new Path()),calls=[],c={save:()=>calls.push('save'),restore:()=>calls.push('restore'),translate:(...v)=>calls.push(['translate',...v]),scale:(...v)=>calls.push(['scale',...v]),fill:(...v)=>calls.push(['fill',...v]),clip:(...v)=>calls.push(['clip',...v])},frame={worldSize:100,groundScaleY:.9,offsetX:10,offsetY:20};d.drawWater(c,frame);d.clipLand(c,frame);assert.equal(calls.find(v=>Array.isArray(v)&&v[0]==='fill')[2],'evenodd');assert.equal(calls.find(v=>Array.isArray(v)&&v[0]==='clip')[2],'evenodd');const path=d.paths.land;for(let i=0;i<100;i++)d.clipLand(c,frame);assert.equal(d.paths.land,path);});
test('overview coastline projection is cached and unwrapped across dateline with holes intact',()=>{const poly=[[[179.99,60],[-179.99,60],[-179.99,60.01],[179.99,60.01],[179.99,60]]],a=overviewPolygon(poly);assert.equal(overviewPolygon(poly),a);assert.ok(a.bounds[2]-a.bounds[0]<.001);assert.equal(a.points[0].length,5);});

test('mainland and island map goal labels use their own land anchors rather than shared bounding centers',async()=>{const {MapExplorer}=await import('../src/map-explorer.js'),{WorldOverview,overviewProject,overviewUnproject}=await import('../src/world-overview.js'),{getMapCellAt}=await import('../src/map-cells.js'),{lonLatToLocal,pointInPolygons}=await import('../src/geometry.js');const cell=getMapCellAt([0,0]),r=(a,b,c,d)=>[[a,b],[c,b],[c,d],[a,d],[a,b]],regions=[{id:'main',representativePoint:[-1000,0],polygons:[[r(-1500,-1500,1500,1500),r(-600,-600,600,600)]]},{id:'island',representativePoint:[0,0],polygons:[[r(-200,-200,200,200)]]}];let features;const picker=Object.create(MapExplorer.prototype),node={textContent:'',classList:{toggle(){}},replaceChildren(){}};Object.assign(picker,{streaming:true,busy:false,boundaries:[{envelopeId:cell.id,center:cell.center,projectionLatitude:cell.projectionLatitude,regions}],streamProgress:regions.map(region=>({sectorId:`${cell.id}/${region.id}`,consumedArea:100,goalArea:100})),map:{getSource:()=>({setData:value=>features=value.features}),getBounds:()=>({getWest:()=>cell.bounds[0],getSouth:()=>cell.bounds[1],getEast:()=>cell.bounds[2],getNorth:()=>cell.bounds[3]}),getCenter:()=>({lng:cell.center[0],lat:cell.center[1]}),getZoom:()=>14},$:()=>node});picker.refresh();const labels=[],ctx=new Proxy({fillText:(...args)=>labels.push(args)},{get:(o,k)=>o[k]??(()=>{})}),map=Object.create(WorldOverview.prototype);Object.assign(map,{ctx,width:1000,height:700,zoom:14,center:overviewProject(cell.center),land:[],features});map.draw();assert.equal(labels.length,2);for(let i=0;i<labels.length;i++){const [,x,y]=labels[i],scale=512*2**14,geo=overviewUnproject([map.center[0]+(x-500)/scale,map.center[1]+(y-350)/scale]),local=lonLatToLocal(geo,cell.center,cell.projectionLatitude);assert.equal(pointInPolygons(local,regions[i].polygons),true);}assert.notEqual(labels[0][1],labels[1][1]);});
