import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,consumeBuilding,serializeRun,compatibleSave,progressPercent,mergeRecord,BALANCE} from '../src/state.js';
const manifest={id:'test',version:'source-1',spawn:[10,20],initialRadius:18,totalBuildingArea:1000,targetPercent:80};
test('area-based reward is exact and stable IDs pay only once',()=>{const run=createRun(manifest),b={id:'way/123',area:250};assert.equal(consumeBuilding(run,b,manifest),true);assert.equal(consumeBuilding(run,b,manifest),false);assert.equal(run.mass,250);assert.equal(run.consumedArea,250);assert.equal(run.radius,Math.sqrt(18**2+BALANCE.growth*250));assert.equal(progressPercent(run,manifest),25);});
test('IndexedDB-serializable run restores IDs, score, time, mass and position',()=>{const run=createRun(manifest);consumeBuilding(run,{id:'way/1',area:500},manifest);run.elapsed=44.1;run.position=[100,200];const saved=JSON.parse(JSON.stringify(serializeRun(run))),restored=createRun(manifest,saved);assert.equal(restored.radius,run.radius);assert.deepEqual([...restored.consumed],[...run.consumed]);assert.equal(restored.elapsed,44.1);assert.deepEqual(restored.position,[100,200]);});
test('incompatible dataset version is detected and resets run only',()=>{const saved={...serializeRun(createRun(manifest)),version:'old',mass:10000,consumed:['way/1']};assert.equal(compatibleSave(saved,manifest),false);const run=createRun(manifest,saved);assert.equal(run.mass,0);assert.equal(run.consumed.size,0);});
test('manifest target is configurable and next level resets growth',()=>{const m={...manifest,targetPercent:65},run=createRun(m);consumeBuilding(run,{id:'way/1',area:649},m);assert.equal(run.completed,false);consumeBuilding(run,{id:'way/2',area:1},m);assert.equal(run.completed,true);const next=createRun({...m,id:'next'});assert.equal(next.radius,18);assert.equal(next.score,0);});
test('personal record keeps fastest completion and highest score',()=>{const run=createRun(manifest);run.elapsed=100;run.score=200;const record=mergeRecord(null,run,manifest);run.elapsed=150;run.score=300;const next=mergeRecord(record,run,manifest);assert.equal(next.elapsed,100);assert.equal(next.score,300);});
