import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {previewEntryErrorMessage} from '../src/renderer-readiness.js';
const source=fs.readFileSync(new URL('../src/main.js',import.meta.url),'utf8'),entry=source.slice(source.indexOf('async function selectStreamedLevel('),source.indexOf('\nasync function selectLevel('));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{resolve,promise};};
function fixture(stage){const reached=deferred(),wait=deferred(),calls=[],node={classList:{contains:()=>false},textContent:''};let held=false;
 const hold=name=>{calls.push(name);if(stage===name&&!held){held=true;reached.resolve();return wait.promise;}return Promise.resolve();};
 const gameRun={mode:'tile-mask-v1',radius:18,elapsed:0,position:[0,0]},context={generation:0,state:'map',streamGame:null,repo:null,run:null,manifest:null,animations:[],levelIndex:0,simulationTime:0,lastTime:0,URL,location:{href:'https://example.test/'},DOMException,console:{error(){}},previewEntryErrorMessage,performance:{now:()=>1},document:{hidden:false},input:{reset(){}},persist:()=>hold('previous-save'),renderer:{ready:true,dispose(){},load:()=>hold('renderer')},absorption:{reset(){}},showScreen(){},catalog:[{id:'cell',center:[30,60],title:'Cell'}],activeCampaign:{title:'City'},streamStore:{},$:()=>node,toast(){},num:String,lonLatToLocal:p=>p,STREAM_MODE:'tile-mask-v1',updateStreamHUD(){},pause(){},mapExplorer:{busy:true,setLoading(){},finishEntry:()=>hold('fade'),element:node,cancelSelection(message){calls.push('error');context.lastError=message;}},openMap:async()=>{}};
 context.StreamingGame=class{constructor(){this.stream={metadata:{tiles:[]}};this.display={};}async prepare(){await hold('nearby-and-save-read');return gameRun;}persist(){return hold('checkpoint');}dispose(){calls.push('dispose');}};
 vm.createContext(context);vm.runInContext(entry,context);return{context,calls,reached,wait,run:()=>context.selectStreamedLevel(0,{entryPoint:[30,60]})};}
for(const stage of ['previous-save','nearby-and-save-read','renderer','checkpoint','fade'])test(`stream entry cancellation is final after ${stage}`,async()=>{const f=fixture(stage),pending=f.run();await f.reached.promise;f.context.generation++;const newRun={id:'replacement'};Object.assign(f.context,{state:'replacement',run:newRun});f.wait.resolve();await pending;assert.equal(f.context.state,'replacement');assert.equal(f.context.run,newRun);});
test('stream entry starts after only nearby authoritative coverage and an atomic checkpoint',async()=>{const f=fixture(null);await f.run();assert.equal(f.context.state,'playing');assert.deepEqual(f.calls,['previous-save','nearby-and-save-read','renderer','checkpoint','fade']);});
test('actual streamed entry refuses an unready renderer before checkpoint or fade',async()=>{const f=fixture(null);f.context.renderer.ready=false;await f.run();assert.equal(f.context.state,'map');assert.ok(!f.calls.includes('checkpoint'));assert.ok(!f.calls.includes('fade'));assert.match(f.context.lastError,/карта не готова/);});
test('actual streamed entry translates GPU initialization failure without calling it a source error',async()=>{const f=fixture(null);f.context.renderer.load=async()=>{const error=new Error('Failed to initialize WebGL');error.name='GPUInitializationError';throw error;};await f.run();assert.equal(f.context.state,'map');assert.match(f.context.lastError,/Для игры нужен WebGL 2/);assert.ok(!f.calls.includes('checkpoint'));});
const choose=source.slice(source.indexOf('async function enterMapCell('),source.indexOf('\nconst mapExplorer='));
test('legacy-save lookup resumes old mode, while new squares use the isolated preview',async()=>{for(const saved of [null,{version:'legacy'}]){const calls=[],context={streamPreview:true,setCampaign(){},baseCatalog:[],saves:{getRun:async()=>saved},mapExplorer:{selectionGeneration:1,busy:true},toast(){},selectLevel:async()=>calls.push('legacy'),selectStreamedLevel:async()=>calls.push('stream')};vm.createContext(context);vm.runInContext(choose,context);await context.enterMapCell({cell:{id:'cell'},campaign:{sectors:[{id:'cell'}]},coordinate:[30,60]});assert.deepEqual(calls,[saved?'legacy':'stream']);}});
test('cancel during legacy-save lookup never enters either mode later',async()=>{const wait=deferred(),calls=[],context={streamPreview:true,setCampaign(){},baseCatalog:[],saves:{getRun:()=>wait.promise},mapExplorer:{selectionGeneration:1,busy:true},toast(){},selectLevel:async()=>calls.push('legacy'),selectStreamedLevel:async()=>calls.push('stream')};vm.createContext(context);vm.runInContext(choose,context);const pending=context.enterMapCell({cell:{id:'cell'},campaign:{sectors:[{id:'cell'}]},coordinate:[30,60]});context.mapExplorer.selectionGeneration++;context.mapExplorer.busy=false;wait.resolve(null);await pending;assert.deepEqual(calls,[]);});
