import test from 'node:test';import assert from 'node:assert/strict';
import {ConsumptionMask,rasterizeCoverageChunk,maskChunksForBounds} from '../src/consumption-mask.js';
import {classifyFootprint,WholeVisualLayer,WHOLE_VISUAL_LIMITS} from '../src/whole-visual-layer.js';
const polygon=[[[[0,0],[10,0],[10,10],[0,10],[0,0]]]],building=(id='house')=>({id,complete:true,polygons:polygon,modelParts:[],bounds:[0,0,10,10],center:[5,5]});
const chunks=()=>maskChunksForBounds([0,0,10,10]).map(key=>[key,rasterizeCoverageChunk(key,polygon)]),flush=()=>new Promise(resolve=>setImmediate(resolve));
function fixture({items=[building()],prepareModel=b=>({id:b.id,sourceVertices:5,preparedVertexCost:5}),raster}={}){const mask=new ConsumptionMask();for(const [key,bits] of chunks())mask.ingestCoverage(key,bits);const display={replacements:new Map(),setReplacements(value){this.replacements=value;}},calls=[],whole={ready:true,buildings:items,async rasterizeSeparately(values){calls.push(values.map(v=>v.id));return raster?raster(values):values.map(b=>({id:b.id,chunks:chunks()}));}},game={whole,mode:'whole',run:{position:[5,5]}},renderer={localViewBounds:()=>[-100,-100,100,100]};const layer=new WholeVisualLayer({mask,display,manifest:{center:[30,60]},prepareModel,prepareClock:()=>0,releaseModel(){},drawModels:(c,models)=>({selectedIds:models.map(m=>m.id),drawnBuildings:models.length,drawnVertices:models.length*5}),});return{mask,display,calls,whole,game,renderer,layer};}
test('classification requires nonempty complete known footprint and distinguishes original partial bites',()=>{const mask=new ConsumptionMask(),data=chunks();assert.equal(classifyFootprint([],mask),'unknown');assert.equal(classifyFootprint(data,mask),'unknown');for(const [key,bits] of data)mask.ingestCoverage(key,bits);assert.equal(classifyFootprint(data,mask),'untouched');mask.consumeCircle([1,1],1);assert.equal(classifyFootprint(data,mask),'partial');mask.consumeBuildingChunks(data);assert.equal(classifyFootprint(data,mask),'gone');mask.evictCoverage(data[0][0]);assert.equal(classifyFootprint(data,mask),'unknown');});
test('known occupancy mismatch cannot create a smooth whole roof',()=>{const f=fixture(),data=chunks();f.mask.ingestCoverage(data[0][0],new Uint8Array(8192));assert.equal(classifyFootprint(data,f.mask),'unknown');});
test('replacement subtracts original footprint bits only and clears after Parts switch',async()=>{const f=fixture();f.layer.sync(f.game,f.renderer,0);await flush();const models=f.layer.sync(f.game,f.renderer,1);f.layer.plan(models,{});assert.equal(models.length,1);assert.deepEqual([...f.display.replacements],chunks());f.game.mode='parts';assert.deepEqual(f.layer.sync(f.game,f.renderer,2),[]);assert.equal(f.display.replacements.size,0);assert.equal(f.layer.cache.size,0);});
test('partial consumption removes smooth model without reclassifying remaining sliver as untouched',async()=>{const f=fixture();f.layer.sync(f.game,f.renderer,0);await flush();assert.equal(f.layer.sync(f.game,f.renderer,1).length,1);f.mask.consumeCircle([1,1],1);assert.equal(f.layer.sync(f.game,f.renderer,2).length,0);assert.equal(f.layer.stats.partialFallbacks,1);});
test('a null prepared model is attempted once, not every idle frame',async()=>{let prepares=0;const f=fixture({prepareModel(){prepares++;return null;}});f.layer.sync(f.game,f.renderer,0);await flush();for(let now=1;now<10;now++)f.layer.sync(f.game,f.renderer,now);assert.equal(prepares,1);});
test('model preparation and stable idle work stay bounded independently of catalog size',async()=>{let prepares=0;const items=Array.from({length:180},(_,i)=>building(`house${i}`)),f=fixture({items,prepareModel:b=>{prepares++;return{id:b.id,sourceVertices:5,preparedVertexCost:5};}});for(let now=0;now<80;now++){f.layer.sync(f.game,f.renderer,now);assert.ok(f.layer.stats.preparedThisFrame<=WHOLE_VISUAL_LIMITS.preparePerFrame);await flush();}const work=[prepares,f.calls.length];for(let now=80;now<180;now++){f.layer.sync(f.game,f.renderer,now);await flush();}assert.deepEqual([prepares,f.calls.length],work);assert.equal(prepares,128);assert.equal(f.calls.length,16);assert.ok(f.layer.bytes<=2*1024*1024);});
test('late worker result cannot repopulate layer after mode switch or disposal',async()=>{let release;const gate=new Promise(r=>release=r),f=fixture({raster:async values=>{await gate;return values.map(b=>({id:b.id,chunks:chunks()}));}});f.layer.sync(f.game,f.renderer,0);f.game.mode='parts';f.layer.sync(f.game,f.renderer,1);release();await flush();assert.equal(f.layer.cache.size,0);assert.equal(f.layer.bytes,0);f.layer.dispose();});
test('thrown model preparation attempts obey the same four-attempt frame limit',async()=>{let calls=0;const f=fixture({items:Array.from({length:8},(_,i)=>building(String(i))),prepareModel(){calls++;throw Error('path allocation');}});f.layer.sync(f.game,f.renderer,0);await flush();f.layer.sync(f.game,f.renderer,1);assert.equal(calls,4);assert.equal(f.layer.stats.preparedThisFrame,4);});
test('complex visual-only fallback is rejected before a worker classification batch',async()=>{const b=building(),ring=Array.from({length:6001},(_,i)=>[i/100,0]);b.polygons=[[ring]];const f=fixture({items:[b]});f.layer.sync(f.game,f.renderer,0);await flush();assert.equal(f.calls.length,0);assert.equal(f.layer.stats.preparedModels,0);});

test('soft preparation deadline defers work without discarding the cached footprint',async()=>{const f=fixture();f.layer.sync(f.game,f.renderer,0);await flush();let reads=0;f.layer.prepareClock=()=>reads++?3:0;assert.equal(f.layer.sync(f.game,f.renderer,1).length,0);assert.equal(f.layer.stats.preparedThisFrame,0);assert.equal(f.layer.cache.size,1);f.layer.prepareClock=()=>0;assert.equal(f.layer.sync(f.game,f.renderer,2).length,1);});


test('resident tall buildings enter the candidate set when only their raised model is visible',async()=>{
  const b=building('tall');b.bounds=[0,-450,10,-430];b.center=[5,-440];b.polygons=[[[[0,-450],[10,-450],[10,-430],[0,-430],[0,-450]]]];b.modelParts=[{polygons:b.polygons,heightMeters:900,minHeightMeters:0}];
  const f=fixture({items:[b]});f.layer.sync(f.game,f.renderer,0);await flush();
  assert.deepEqual(f.calls,[['tall']]);assert.equal(f.layer.sync(f.game,f.renderer,1).length,1);
  assert.equal(f.whole.buildings.length,1,'only the existing resident catalog is used');
});
