import test from 'node:test';import assert from 'node:assert/strict';
import {StreamingGame} from '../src/streaming-game.js';import {rasterizeCoverageChunk,maskChunksForBounds} from '../src/consumption-mask.js';
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{resolve,promise};};
const shape=(id,x0,y0,x1,y1)=>({id,complete:true,bounds:[x0,y0,x1,y1],polygons:[[[[x0,y0],[x1,y0],[x1,y1],[x0,y1],[x0,y0]]]],center:[(x0+x1)/2,(y0+y1)/2],radius:Math.hypot(x1-x0,y1-y0)/2});
const small=shape('small',-4,-4,4,4),large=shape('large',-40,-4,40,4);
const chunks=buildings=>{const all=new Map();for(const b of buildings)for(const key of maskChunksForBounds(b.bounds)){const bits=rasterizeCoverageChunk(key,b.polygons),old=all.get(key)||new Uint8Array(8192);for(let i=0;i<bits.length;i++)old[i]|=bits[i];all.set(key,old);}return[...all];};
function fixture({buildings=[small],wait=null,mode='whole'}={}){let calls=0;const whole={ready:true,buildings,update:async()=>{},rasterize:async values=>{calls++;if(wait)await wait.promise;return chunks(values);},dispose(){}};const store={load:async()=>({run:null,masks:[]}),save:async()=>{}},game=new StreamingGame({landPreparation:null,sector:{id:'test-whole',center:[30,60]},store,mode,displayFactory:()=>({changed(){},dispose(){}}),wholeFactory:()=>whole,streamFactory:({mask})=>({source:{},metadata:{},prepare:async()=>{for(const[key,bits]of chunks(buildings))mask.ingestCoverage(key,bits);},update:async()=>{},covers:()=>true,dispose(){}})});return{game,whole,get calls(){return calls;}};}
const settle=()=>new Promise(r=>setImmediate(r));
test('whole mode consumes every cell of a fitting house atomically, then never rasterizes it each frame',async()=>{const f=fixture();await f.game.prepare();assert.equal(f.game.tick(.01,1,[0,0]).area,0);await settle();assert.equal(f.game.run.consumedArea,0);assert.equal(f.game.tick(.01,2,[0,0]).area,64);assert.equal(f.game.mask.consumedAreaM2,64);for(let n=3;n<100;n++)f.game.tick(.01,n,[0,0]);assert.equal(f.calls,1);f.game.dispose();});
test('oversized whole contour is passable but cannot be eaten even when its center overlaps hole',async()=>{const f=fixture({buildings:[large]});await f.game.prepare();const p=[...f.game.run.position];f.game.tick(.01,1,[1,0]);await settle();assert.ok(f.game.run.position[0]>p[0]);assert.equal(f.calls,0);assert.equal(f.game.run.consumedArea,0);f.game.dispose();});
for(const action of ['pause','mode','away','dispose','catalog'])test(`pending whole raster cannot reward after ${action}`,async()=>{const wait=deferred(),f=fixture({wait});await f.game.prepare();f.game.tick(.01,1,[0,0]);if(action==='pause')f.game.suspend();if(action==='mode')f.game.setMode('parts');if(action==='away')f.game.run.position=[100,0];if(action==='dispose')f.game.dispose();if(action==='catalog')f.whole.buildings=[{...small,id:'new'}];wait.resolve();await settle();if(action!=='mode')f.game.tick(.01,2,[0,0]);assert.equal(f.game.run.consumedArea,0);assert.equal(f.game.mask.consumedAreaM2,0);f.game.dispose();});
test('Parts→Whole checks original footprint, then awards only remaining cells once it fits',async()=>{const f=fixture({buildings:[large],mode:'parts'});await f.game.prepare();f.game.tick(.01,1,[0,0]);const bite=f.game.run.consumedArea;assert.ok(bite>0&&bite<640);f.game.setMode('whole');await f.game.prepareWhole();f.game.tick(.01,2,[0,0]);await settle();assert.equal(f.game.run.consumedArea,bite);f.game.run.radius=50;f.game.tick(.01,3,[0,0]);await settle();f.game.tick(.01,4,[0,0]);assert.equal(f.game.run.consumedArea,640);assert.equal(f.game.mask.consumedAreaM2,640);f.game.setMode('parts');f.game.tick(.01,5,[0,0]);assert.equal(f.game.run.consumedArea,640);f.game.dispose();});
test('mode change cancels an unfinished budgeted Parts sweep before any Whole tick',async()=>{const f=fixture({mode:'parts'});await f.game.prepare();f.game.mask.consumeSweep=()=>({areaM2:0,changedChunks:[],complete:false,cursor:{}});f.game.tick(.01,1,[0,0]);assert.ok(f.game.job);f.game.setMode('whole');assert.equal(f.game.job,null);await f.game.prepareWhole();f.game.tick(.01,2,[0,0]);f.game.dispose();});
test('border outline shows the complete outside footprint, then disappears when its own remaining area is zero',async()=>{const border=shape('border',1450,-4,1550,4),f=fixture({buildings:[border]});await f.game.prepare();f.game.run.position=[1500,0];f.game.tick(.01,1,[0,0]);await settle();let outlines=f.game.boundaryOutlines();assert.equal(outlines.length,1);assert.equal(outlines[0].bounds[2],1550);assert.equal(outlines[0].fits,false);f.game.run.radius=100;f.game.tick(.01,2,[0,0]);await settle();f.game.tick(.01,3,[0,0]);assert.equal(f.game.run.consumedArea,400);assert.deepEqual(f.game.boundaryOutlines(),[]);const saved=[...f.game.mask.consumed].map(([key,value])=>[key,new Uint8Array(value.bits)]);f.game.dispose();const next=fixture({buildings:[border]});await next.game.prepare();next.game.mask.restoreConsumed(saved);next.game.run.position=[1500,0];next.game.tick(.01,1,[0,0]);await settle();assert.deepEqual(next.game.boundaryOutlines(),[]);next.game.dispose();});
