/** Large imported geometry is persisted separately from tiny campaign metadata. */
export class CityCache {
  constructor(){this.db=null;}
  async init(){if(this.db)return this;this.db=await new Promise((resolve,reject)=>{const r=indexedDB.open('city-eater-cities-v1',1);r.onupgradeneeded=()=>{for(const name of ['campaigns','sectors','chunks'])r.result.createObjectStore(name,{keyPath:'id'});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return this;}
  async request(store,method,value){await this.init();return new Promise((resolve,reject)=>{const t=this.db.transaction(store,method==='get'||method==='getAll'?'readonly':'readwrite'),r=t.objectStore(store)[method](value);let result;r.onsuccess=()=>result=r.result;t.oncomplete=()=>resolve(result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
  campaigns(){return this.request('campaigns','getAll');}getCampaign(id){return this.request('campaigns','get',id);}putCampaign(campaign){return this.request('campaigns','put',{...campaign,updatedAt:Date.now()});}
  getSector(id){return this.request('sectors','get',id);}
  async loadChunk(sectorId,chunk){const data=await this.request('chunks','get',`${sectorId}::${chunk.id}`);if(!data)throw new Error('Участок не найден в локальном хранилище. Загрузите его заново.');return data.data;}
  async putSector(campaignId,result){await this.init();const {manifest,chunks,background,provenance}=result;return new Promise((resolve,reject)=>{const t=this.db.transaction(['sectors','chunks'],'readwrite');t.objectStore('sectors').put({id:manifest.id,campaignId,manifest:{...manifest,campaignId,background},provenance,createdAt:Date.now()});for(const [key,value] of Object.entries(chunks))t.objectStore('chunks').put({id:`${manifest.id}::${key}`,sectorId:manifest.id,data:value});t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
  async updateProgress(campaignId,sectorId,progress){await this.init();return new Promise((resolve,reject)=>{const tx=this.db.transaction('campaigns','readwrite'),store=tx.objectStore('campaigns'),request=store.get(campaignId);let updated;request.onsuccess=()=>{const c=request.result;if(!c)return;c.progress??={};const prior=c.progress[sectorId]||{},sameVersion=!progress.version||!prior.version||progress.version===prior.version,base=sameVersion?prior:{};c.progress[sectorId]={...base,...progress};if(sameVersion){c.progress[sectorId].completed=Boolean(base.completed||progress.completed);c.progress[sectorId].consumedArea=Math.max(base.consumedArea||0,progress.consumedArea||0);}c.updatedAt=Date.now();updated=c;store.put(c);};tx.oncomplete=()=>resolve(updated);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
}
