import '@fontsource/manrope/400.css';
import '@fontsource/manrope/600.css';
import '@fontsource/manrope/800.css';
import '@fontsource/unbounded/700.css';
import '@fontsource/unbounded/900.css';
import './style.css';
import {MapRenderer} from './renderer.js';
import {BuildingRepository} from './repository.js';
import {HoleController} from './input.js';
import {AudioSystem} from './audio.js';
import {SaveSystem} from './storage.js';
import {createRun,consumeBuilding,serializeRun,progressPercent,compatibleSave,mergeRecord} from './state.js';
import {polygonFitsCircle,lonLatToLocal,localToLonLat} from './geometry.js';
import {advanceHole} from './motion.js';
import {AbsorptionSystem} from './absorption.js';
import {CheckpointQueue} from './checkpoints.js';
import {CityCache} from './city-cache.js';
import {OverpassClient,escapeHTML} from './overpass-client.js';
import {SectorLoader} from './sector-loader.js';
import {CityPicker} from './city-picker.js';
import {MapExplorer} from './map-explorer.js';
import {cameraMetrics} from './camera.js';
import {summarizeCampaign} from './city-campaign.js';
const $=s=>document.querySelector(s);
const icon={pause:'<span class="pause-icon"><i></i><i></i></span>',play:'<span>↗</span>',sound:'♪',arrow:'↗'};
$('#app').innerHTML=`
  <header id="topbar"><a class="brand" href="#" aria-label="CITY EATER, главное меню"><span class="brand-orbit"></span>CITY EATER<span class="brand-dot">06</span></a><div class="top-right"><span class="edition">REAL CITY. REAL APPETITE.</span><button id="pause" class="icon-button" aria-label="Пауза">${icon.pause}</button></div></header>
  <section id="hud" class="hidden" aria-label="Игровые показатели"><div class="progress-card"><div class="progress-label"><span>ПОГЛОЩЕНО</span><span>ЦЕЛЬ <b id="target-value">80</b>%</span></div><div class="progress-number"><span id="progress-value">0.00</span><small>%</small></div><div class="progress-track"><i id="progress-fill"></i><span></span></div><span class="mobile-target">из <b id="mobile-target">80</b>%</span><span id="mobile-radius" class="mobile-radius">18 м</span><button id="stats-toggle" aria-expanded="false" aria-controls="extra-stats" aria-label="Показать показатели">•••</button><div class="hud-location"><i></i><span id="hud-level"></span><span>100 КМ²</span></div></div><div id="extra-stats" class="stats-card"><div><span>РАДИУС</span><b id="radius-value">18 <small>м</small></b></div><div><span>ЗДАНИЯ</span><b id="count-value">0</b></div><div><span>ОЧКИ</span><b id="score-value">0</b></div><div><span>ВРЕМЯ</span><b id="time-value">00:00</b></div></div></section>
  <div id="game-bottom" class="hidden"><div class="controls-help"><span class="keys">W A S D</span><span class="desktop-help">Двигайся и поглощай</span><span class="touch-help">Коснись карты и тяни</span></div><div id="target-hint"></div><div class="arena-mini"><span class="north">N ↑</span><div><i id="mini-player"></i></div><small>10 × 10 КМ</small></div></div>
  <section id="menu" class="screen"><div class="menu-copy"><div class="eyebrow"><i></i>ОДИНОЧНАЯ АРКАДА · OPENSTREETMAP</div><h1>ГОРОД.<br>НА ОБЕД<span>.</span></h1><p class="lead">Начни с малого.<br>Вырастай до немыслимого.</p><p class="description">Настоящие улицы. Настоящие здания.<br>Одна очень голодная чёрная дыра.</p><div class="menu-actions"><button id="play" class="primary" disabled>Загружаем город… <span class="button-arrow">↗</span></button><button id="menu-map" class="text-button map-menu-back">← К карте районов</button><div class="menu-proof"><span class="proof-dot"></span><span>Без таймера. В своём ритме.</span></div></div></div><aside class="level-panel panel"><div class="section-label"><span>ВЫБЕРИ СВОЮ КАРТУ</span><span id="level-number">01 / 02</span></div><div id="levels"></div><button id="city-open" class="city-open-button">Выбрать любой город <span>↗</span></button><div id="campaign-progress"></div><div class="level-facts"><div><b>100</b><span>КМ² АРЕНЫ</span></div><div><b>80<span>%</span></b><span>ЦЕЛЬ УРОВНЯ</span></div><div><b>∞</b><span>ВРЕМЕНИ</span></div></div><div class="how"><span class="how-number">01</span><p>Двигайся к светлым зданиям.<br><strong>Они уже тебе по размеру.</strong></p></div><div class="how"><span class="how-number">02</span><p>Поглощай, расти, исследуй.<br><strong>Через большие можно пройти.</strong></p></div><div class="settings"><label>Звук <button id="sound-toggle" class="toggle" aria-label="Переключить звук" aria-pressed="true">Вкл</button></label><label>Графика <select id="quality" aria-label="Качество графики"><option value="high">Высокая</option><option value="low">Экономная</option></select></label></div></aside><div class="menu-footer"><span>САНКТ-ПЕТЕРБУРГ И ОБЛАСТЬ</span><button id="about-open" class="text-button">О картах и игре ↗</button></div></section>
  <section id="pause-screen" class="screen modal-screen hidden" role="dialog" aria-modal="true" aria-labelledby="pause-title"><div class="modal panel"><div class="eyebrow">МОЖНО НЕ СПЕШИТЬ</div><h2 id="pause-title">Город подождёт.</h2><p id="pause-note">Прогресс сохраняется автоматически.</p><button id="resume" class="primary">Продолжить <span>↗</span></button><button id="to-menu" class="secondary">К карте</button><button id="restart" class="text-button">Начать заново</button></div></section>
  <section id="result" class="screen modal-screen hidden" role="dialog" aria-modal="true" aria-labelledby="result-title"><div class="modal result-modal panel"><div class="victory-orbit"></div><div class="eyebrow">ПРЕКРАСНЫЙ АППЕТИТ</div><h2 id="result-title">Город съеден.</h2><p id="result-place"></p><div class="result-grid" id="result-stats"></div><div class="record" id="record"></div><button id="next-level" class="primary">Следующий город <span>↗</span></button><button id="replay" class="secondary">Ещё раз</button><button id="result-menu" class="text-button">К карте</button></div></section>
  <section id="about" class="screen modal-screen hidden" role="dialog" aria-modal="true" aria-labelledby="about-title"><div class="modal about-modal panel"><div class="eyebrow">СОЗДАНО ИЗ НАСТОЯЩЕГО</div><h2 id="about-title">Это реальный город.</h2><p>Каждое игровое здание взято из OpenStreetMap. Никаких сгенерированных домов или соперников. Игровой квадрат — ровно 10 000 × 10 000 метров в локальных координатах.</p><p>Готовые карты доставляются с сайта в PMTiles. Для выбранного города мы один раз загружаем OSM каждого участка и готовим фон GeoJSON прямо в браузере. Участки, съеденные здания и прогресс города сохраняются в IndexedDB на этом устройстве.</p><p class="fine-print">Данные © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a>, <a href="https://opendatacommons.org/licenses/odbl/1-0/" target="_blank" rel="noopener">ODbL 1.0</a>. MapLibre GL JS · PMTiles.<br>Полнота карты зависит от OSM. Прототип v0.7. Баланс ещё настраивается.</p><a class="data-link" href="./data/README.md" target="_blank">Источники и версия данных ↗</a><button id="about-close" class="primary">Понятно <span>↗</span></button></div></section>
  <div id="loading" class="loading hidden"><span></span><p id="loading-text">Собираем настоящий город…</p><button id="cancel-import" class="secondary hidden">Отменить загрузку</button></div><div id="toast" role="status" aria-live="polite"></div><div id="network" class="hidden">Подгружаем район…</div><div id="joystick"><div id="joystick-knob"></div></div><div id="fps" class="hidden"></div>`;

let catalog=[],baseCatalog=[],activeCampaign=null,levelIndex=0,manifest=null,run=null,repo=null,state='boot',unlocked=0,animations=[],simulationTime=0,lastTime=performance.now(),lastUI=0,lastStream=0,lastSave=0,streaming=false,generation=0,previewRadius=18,mapErrorCount=0,toastTimer,completing=false,fpsSamples=[],lastHint=0,hintCandidates=[];
const num=v=>Math.round(v).toLocaleString('ru-RU');
const time=v=>`${String(Math.floor(v/60)).padStart(2,'0')}:${String(Math.floor(v%60)).padStart(2,'0')}`;
function toast(text,long=false){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),long?8000:4000);}
const saves=new SaveSystem(text=>toast(text,true));
const cityCache=new CityCache(),osmClient=new OverpassClient(),sectorLoader=new SectorLoader(cityCache,osmClient),absorption=new AbsorptionSystem();
const checkpoints=new CheckpointQueue(async snapshot=>{await saves.saveRun(snapshot);if(snapshot.campaignId)await cityCache.updateProgress(snapshot.campaignId,snapshot.levelId,{consumedArea:snapshot.consumedArea,completed:snapshot.completed,version:snapshot.version}).catch(()=>{});});
const renderer=new MapRenderer(message=>{if(++mapErrorCount<3)toast('Не удалось загрузить часть фоновой карты. Проверь соединение.',true);console.warn(message);});
const audio=new AudioSystem();
let settings={sound:true,quality:'high'};try{settings={...settings,...JSON.parse(localStorage.getItem('city-eater-settings')||'{}')};}catch{}
function saveSettings(){try{localStorage.setItem('city-eater-settings',JSON.stringify(settings));}catch{}}
function applySettings(){audio.enabled=settings.sound;$('#sound-toggle').textContent=settings.sound?'Вкл':'Выкл';$('#sound-toggle').setAttribute('aria-pressed',String(settings.sound));$('#quality').value=settings.quality;renderer.setQuality(settings.quality);}
const input=new HoleController(()=>state==='playing',()=>{if(state==='playing')pause();else if(state==='paused')resume();});
function showScreen(id){for(const el of document.querySelectorAll('.screen'))el.classList.toggle('hidden',el.id!==id);const playing=['playing','paused','result'].includes(state);$('#hud').classList.toggle('hidden',!playing);$('#game-bottom').classList.toggle('hidden',state!=='playing');$('#pause').classList.toggle('hidden',!['playing','paused'].includes(state));document.body.dataset.state=state;}
function campaignNext(c=activeCampaign){const i=c?.sectors.findIndex(sector=>!c.progress?.[sector.id]?.completed);return i===-1?0:(i??0);}
function canSelect(entry,index){return entry.custom?true:index<=unlocked;}
function renderLevels(){
  const currentCustom=levelIndex>=baseCatalog.length?levelIndex:baseCatalog.length+campaignNext();
  const visible=catalog.map((level,i)=>({level,i})).filter(({level,i})=>!level.custom||i===currentCustom);
  $('#levels').innerHTML=visible.map(({level,i})=>{const locked=!canSelect(level,i);return `<button class="level ${i===levelIndex?'selected':''}" data-index="${i}" ${locked?'disabled':''}><span class="level-index">${level.custom?'↗':String(i+1).padStart(2,'0')}</span><span class="level-name"><strong>${escapeHTML(level.custom?activeCampaign.title:level.title)}</strong><small>${escapeHTML(locked?'Пройди предыдущий город':level.custom?`Участок ${level.sectorIndex+1} / ${activeCampaign.sectors.length}`:level.subtitle||'Настоящий город · 100 км²')}</small></span><span class="level-symbol">${locked?'⊗':i===levelIndex?'↗':'→'}</span></button>`;}).join('');
  $('#level-number').textContent=catalog[levelIndex]?.custom?`СЕКТОР ${catalog[levelIndex].sectorIndex+1}`:`${String(levelIndex+1).padStart(2,'0')} / ${String(baseCatalog.length).padStart(2,'0')}`;
  if(activeCampaign){const summary=summarizeCampaign(activeCampaign,activeCampaign.progress);$('#campaign-progress').textContent=`${activeCampaign.title}: ${summary.completed} / ${summary.total} участков пройдено`;}
  else $('#campaign-progress').textContent='';
  for(const button of document.querySelectorAll('.level'))button.onclick=()=>{if(Number(button.dataset.index)!==levelIndex)selectLevel(Number(button.dataset.index));};
}
function setCampaign(campaign){activeCampaign=campaign;catalog=[...baseCatalog,...(campaign?campaign.sectors.map((sector,index)=>({...sector,custom:true,sectorIndex:index,subtitle:`Участок ${index+1} / ${campaign.sectors.length}`})):[])];}
async function activateCampaign(campaign,index=0){mapExplorer.view={center:campaign.center,zoom:10,campaignId:campaign.id};mapExplorer.returnView={...mapExplorer.view};await persist();setCampaign(await cityCache.getCampaign(campaign.id)||campaign);await selectLevel(baseCatalog.length+index,{start:true});}
function nextLevelIndex(){const entry=catalog[levelIndex];if(entry?.custom)return entry.sectorIndex+1<activeCampaign.sectors.length?levelIndex+1:-1;return levelIndex+1<baseCatalog.length?levelIndex+1:-1;}
function updateNextButton(){const index=nextLevelIndex();$('#next-level').classList.toggle('hidden',index<0);$('#next-level').textContent=index>=0?`${catalog[index].custom?'Следующий участок':'Дальше'}: ${catalog[index].custom?catalog[index].sectorIndex+1:catalog[index].title} ↗`:'';}
async function fetchJSON(url){const response=await fetch(url);if(!response.ok)throw new Error(`HTTP ${response.status}: ${url}`);return response.json();}
async function selectLevel(index,{restart=false,start=false,fromMap=false,entryPoint=null}={}){
  const token=++generation;state=fromMap?'map-loading':'loading';input.reset();hintCandidates.length=0;await persist();if(token!==generation)return;levelIndex=index;state=fromMap?'map-loading':'loading';input.reset();showScreen(fromMap?null:'menu');renderLevels();$('#loading').classList.toggle('hidden',fromMap);$('#play').disabled=true;document.querySelector('#startup-error')?.remove();absorption.reset();animations=absorption.animations;document.body.classList.remove('stats-open');$('#stats-toggle').setAttribute('aria-expanded','false');repo?.dispose();
  try{
    const entry=catalog[index],loadingCampaign=activeCampaign;let nextManifest,base,loadChunk;
    $('#loading-text').textContent='Собираем настоящий город…';$('#cancel-import').classList.toggle('hidden',!entry.custom);
    if(entry.custom){const stored=await sectorLoader.load(loadingCampaign,entry,(text,details)=>{if(token!==generation)return;$('#loading-text').textContent=text;if(fromMap)mapExplorer.setLoading(text,details);});if(token!==generation)return;nextManifest=stored.manifest;nextManifest.campaignId=loadingCampaign.id;base=new URL('./data/',location.href);loadChunk=chunk=>cityCache.loadChunk(entry.id,chunk);const refreshedCampaign=await cityCache.getCampaign(loadingCampaign.id);if(token!==generation)return;activeCampaign=refreshedCampaign||loadingCampaign;if(!nextManifest.buildingCount){if(fromMap)mapExplorer.hide();await showEmptySector(entry,nextManifest,token);return;}if(nextManifest.warnings?.length)toast(nextManifest.warnings[0],true);}
    else{const manifestUrl=new URL(entry.manifest||`./${entry.id}/manifest.json`,new URL('./data/',location.href));nextManifest=await fetchJSON(manifestUrl);base=new URL('.',manifestUrl);}
    if(token!==generation)return;nextManifest.id??=entry.id;nextManifest.title??=entry.title;
    let saved=restart?null:await saves.getRun(nextManifest.id);if(token!==generation)return;
    if(saved&&!compatibleSave(saved,nextManifest)){toast('Карта обновилась. Это прохождение сброшено, личные рекорды сохранены.',true);await saves.deleteRun(nextManifest.id);if(token!==generation)return;saved=null;}
    if(!saved&&entry.custom&&nextManifest.suitability?.initialEdibleBuildingCount===0&&nextManifest.suitability?.suggestedInitialRadius){const radius=nextManifest.suitability.suggestedInitialRadius;if(!fromMap&&!confirm(`В этом участке нет зданий для начального радиуса 18 м. Начать с радиусом ${radius} м? Можно отменить и выбрать другой участок.`)){state='menu';showScreen('menu');repo=null;$('#play').disabled=false;$('#play').innerHTML='Выбрать начало <span>↗</span>';return;}nextManifest.initialRadius=radius;if(fromMap)toast(`Для реальных зданий этого района стартовый радиус — ${radius} м.`,true);}
    manifest=nextManifest;run=createRun(manifest,saved);if(!saved&&fromMap&&entryPoint)run.position=advanceHole(lonLatToLocal(entryPoint,manifest.center,manifest.projectionLatitude),[0,0],run.radius,5000);if(manifest.campaignId)run.campaignId=manifest.campaignId;simulationTime=run.elapsed*1000;previewRadius=run.radius;completing=false;
    repo=new BuildingRepository(manifest,base,run.consumed,()=>renderer.syncBuildings(repo),{loadChunk});
    if(fromMap){mapExplorer.setLoading('Готовим ближайшие здания…',{phase:'ready'});const center=localToLonLat(run.position,manifest.center,manifest.projectionLatitude);mapExplorer.alignEntry(center,cameraMetrics(run.radius,renderer.width,renderer.height,center[1],manifest.projectionLatitude).zoom);}repo.setViewport(renderer.width,renderer.height);await renderer.load(manifest,base,run);if(token!==generation)return;
    await repo.update(run.position,run.radius);if(token!==generation)return;
    renderer.syncBuildings(repo);renderer.setRadius(run.radius);$('#hud-level').textContent=manifest.title;$('#target-value').textContent=manifest.targetPercent??manifest.target??80;$('#mobile-target').textContent=manifest.targetPercent??manifest.target??80;
    state=fromMap?'map-loading':'menu';showScreen(fromMap?null:'menu');$('#play').disabled=false;$('#play').innerHTML=`${saved&&!run.completed?'Продолжить':'Поглотить город'} <span class="button-arrow">↗</span>`;
    updateHUD();await saves.selectLevel(manifest.id).catch(()=>{});if(restart)await persist();if(start){if(fromMap)await mapExplorer.finishEntry();if(token!==generation)return;await play();}
  }catch(error){if(token!==generation)return;console.error(error);if(catalog[index]?.custom&&error.name!=='AbortError'){const updated=await cityCache.updateProgress(activeCampaign.id,catalog[index].id,{loadError:error.message}).catch(()=>activeCampaign);if(token!==generation)return;activeCampaign=updated;}const webgl=/webgl|graphics context|initialize.*gl/i.test(error.message||'');if(fromMap){state='map';showScreen(null);repo?.dispose();renderer.dispose();mapExplorer.cancelSelection(webgl?'Для игры нужен WebGL 2. В этом браузере графика недоступна.':error.name==='AbortError'?'Загрузка отменена.':error.message);repo=null;return;}state='menu';showScreen('menu');$('#play').disabled=webgl;$('#play').innerHTML=webgl?'WebGL недоступен':'Повторить загрузку <span>↻</span>';if(webgl){const note=document.createElement('p');note.id='startup-error';note.className='startup-error';note.setAttribute('role','alert');note.textContent='В этом браузере отключена или недоступна 3D-графика WebGL. Для карты нужен WebGL 2. Открой игру в другом современном браузере или на устройстве, где WebGL доступен.';$('.menu-actions').append(note);}else toast(error.name==='AbortError'?'Загрузка отменена. Готовые карты доступны сразу.':catalog[index]?.custom?error.message:'Город не загрузился. Проверь соединение и повтори попытку.',true);repo=null;}
  finally{if(token===generation){$('#loading').classList.add('hidden');$('#cancel-import').classList.add('hidden');}}
}
async function play(){if(!repo||!renderer.ready){await selectLevel(levelIndex,{start:true});return;}if(run.completed){await selectLevel(levelIndex,{restart:true,start:true});return;}audio.unlock();state='playing';input.reset();showScreen(null);lastTime=performance.now();$('#pause').focus({preventScroll:true});if(document.hidden)pause('Игра была подготовлена, пока вкладка была скрыта.');}
function pause(note='Прогресс сохраняется автоматически.'){if(state!=='playing')return;state='paused';input.reset();$('#pause-note').textContent=note;showScreen('pause-screen');persist();$('#resume').focus({preventScroll:true});}
function resume(){if(state!=='paused')return;audio.unlock();state='playing';showScreen(null);lastTime=performance.now();$('#pause').focus({preventScroll:true});}
async function persist(){if(run&&manifest){try{await checkpoints.flush(run);}catch{}}}
function updateHUD(){if(!run||!manifest)return;const percent=progressPercent(run,manifest);$('#progress-value').textContent=percent.toFixed(2);$('#progress-fill').style.width=`${Math.min(100,percent)}%`;$('#radius-value').innerHTML=`${num(run.radius)} <small>м</small>`;$('#mobile-radius').textContent=`${num(run.radius)} м`;document.body.classList.toggle('has-progress',run.consumed.size>0);$('#count-value').textContent=num(run.consumed.size);$('#score-value').textContent=num(run.score);$('#time-value').textContent=time(run.elapsed);$('#mini-player').style.left=`${(run.position[0]+5000)/100}%`;$('#mini-player').style.top=`${(5000-run.position[1])/100}%`;
  if(state==='playing'&&repo&&performance.now()-lastHint>650){lastHint=performance.now();let nearest=null,distance=Infinity;for(const b of repo.near(run.position,Math.max(800,run.radius*2),hintCandidates)){if(b.radius>run.radius*1.06)continue;const d=Math.hypot(b.center[0]-run.position[0],b.center[1]-run.position[1]);if(d<distance){nearest=b;distance=d;}}
  if(!nearest)for(const b of repo.buildings.values()){if(b.radius>run.radius*1.06)continue;const d=Math.hypot(b.center[0]-run.position[0],b.center[1]-run.position[1]);if(d<distance){nearest=b;distance=d;}}hintCandidates.length=0;
  $('#target-hint').innerHTML=nearest&&distance>run.radius*1.8?`<span style="transform:rotate(${Math.atan2(nearest.center[0]-run.position[0],nearest.center[1]-run.position[1])*180/Math.PI}deg)">↑</span> ЦЕЛЬ · ${num(distance)} М`:run.consumed.size<4?'Светлые здания уже тебе по размеру':'';}
}
async function complete(){if(completing)return;const completedRun=run,completedManifest=manifest,completedIndex=levelIndex,token=generation;completing=true;state='result';input.reset();showScreen('result');await persist();if(completedManifest.campaignId){const updated=await cityCache.updateProgress(completedManifest.campaignId,completedManifest.id,{completed:true,consumedArea:completedRun.consumedArea,totalBuildingArea:completedManifest.totalBuildingArea,version:completedManifest.version});if(token===generation)activeCampaign=updated;}else{unlocked=Math.max(unlocked,completedIndex+1);await saves.unlock(unlocked).catch(()=>{});}if(token!==generation)return;$('#replay').classList.remove('hidden');$('#result-title').textContent=completedManifest.campaignId?'Участок съеден.':'Город съеден.';const old=await saves.getRecord(completedManifest.id).catch(()=>null),record=mergeRecord(old,completedRun,completedManifest);await saves.saveRecord(completedManifest.id,record).catch(()=>{});if(token!==generation)return;$('#result-place').textContent=`${completedManifest.title} · ${progressPercent(completedRun,completedManifest).toFixed(2)}% площади зданий`;
  $('#result-stats').innerHTML=[['ПОГЛОЩЕНО',`${(completedRun.consumedArea/1e6).toFixed(2)} км²`],['ЗДАНИЯ',num(completedRun.consumed.size)],['ВРЕМЯ',time(completedRun.elapsed)],['ОЧКИ',num(completedRun.score)],['МАКС. РАДИУС',`${num(completedRun.radius)} м`],['ПРОГРЕСС',`${progressPercent(completedRun,completedManifest).toFixed(2)}%`]].map(([label,value])=>`<div><span>${label}</span><b>${value}</b></div>`).join('');$('#record').textContent=!old||completedRun.elapsed<old.elapsed?`✦ Новый личный рекорд · ${time(completedRun.elapsed)}`:`Личный рекорд · ${time(record.elapsed)}`;
  updateNextButton();renderLevels();
}
function tick(now){const rawDelta=Math.max(0,(now-lastTime)/1000),dt=Math.min(.04,rawDelta);lastTime=now;fpsSamples.push(rawDelta);if(fpsSamples.length>60)fpsSamples.shift();
  if(state==='playing'&&run&&repo){simulationTime+=dt*1000;run.elapsed+=dt;const direction=input.direction();
    const speed=95+Math.min(1400,run.radius*.75),delta=[direction[0]*speed*dt,direction[1]*speed*dt];
    const proposed=[run.position[0]+delta[0],run.position[1]+delta[1]];
    const covered=repo.covers(proposed,run.radius+30);
    run.position=advanceHole(run.position,covered?delta:[0,0],run.radius,5000);
    $('#network').classList.toggle('hidden',covered);
    const result=absorption.step(run,repo,manifest,simulationTime,settings.quality);animations=absorption.animations;
    if(result.changed){renderer.setRadius(run.radius);audio.absorb(run.radius);checkpoints.request(run);}
    if(result.started||result.changed)renderer.syncBuildings(repo);
    if(run.completed&&absorption.pendingCount===0)complete();
    if(now-lastStream>450&&!streaming){lastStream=now;streaming=true;const current=repo;current.setViewport(renderer.width,renderer.height);current.update(run.position,run.radius,direction).catch(error=>{if(current===repo){pause('Часть района не загрузилась. Проверь интернет и продолжи.');toast(error.message,true);}}).finally(()=>{streaming=false;$('#network').classList.add('hidden');});}
    if(now-lastSave>2000){lastSave=now;checkpoints.request(run);}
    renderer.camera(run.position,run.radius,dt);renderer.render(run,animations,simulationTime,direction);
  }else if(run&&renderer.ready&&!['map','map-loading','city-picker'].includes(state)){if(state==='menu')renderer.camera(run.position,run.radius,dt);renderer.render(run,animations,simulationTime);}
  if(now-lastUI>120){lastUI=now;updateHUD();if($('#qa-city-metrics'))$('#qa-city-metrics').textContent=`OSM requests: ${osmClient.requestCount} | cached: ${sectorLoader.stats.cacheHits} | imported: ${sectorLoader.stats.imports}`;if(new URLSearchParams(location.search).has('test'))$('#fps').textContent=`${Math.round(fpsSamples.length/(fpsSamples.reduce((a,b)=>a+b,0)||1))} fps | ${repo?.buildings.size||0} objects | ${repo?.chunks.size||0} chunks`;}
  requestAnimationFrame(tick);
}
$('#stats-toggle').onclick=()=>{const open=document.body.classList.toggle('stats-open');$('#stats-toggle').setAttribute('aria-expanded',String(open));$('#stats-toggle').setAttribute('aria-label',open?'Скрыть показатели':'Показать показатели');};
$('#play').onclick=()=>repo?play():openMap();$('#pause').onclick=()=>state==='playing'?pause():resume();$('#resume').onclick=resume;
$('#to-menu').onclick=()=>openMap();$('#menu-map').onclick=()=>openMap();
$('#restart').onclick=()=>{if(confirm('Начать этот город заново? Текущее прохождение будет заменено. Рекорд останется.'))selectLevel(levelIndex,{restart:true,start:true});};
$('#replay').onclick=()=>selectLevel(levelIndex,{restart:true,start:true});$('#next-level').onclick=()=>{const next=nextLevelIndex();if(next>=0)selectLevel(next,{start:true});};$('#result-menu').onclick=()=>openMap();
$('.brand').onclick=e=>{e.preventDefault();if(state==='playing')pause();else if(state==='paused'){$('#to-menu').click();}};
$('#sound-toggle').onclick=()=>{settings.sound=!settings.sound;applySettings();saveSettings();audio.unlock();};$('#quality').onchange=e=>{settings.quality=e.target.value;applySettings();saveSettings();};
$('#about-open').onclick=()=>{$('#about').classList.remove('hidden');$('#about-close').focus({preventScroll:true});};$('#about-close').onclick=()=>{$('#about').classList.add('hidden');$('#about-open').focus({preventScroll:true});};
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause('Игра была приостановлена, пока вкладка была скрыта.');});
window.addEventListener('pagehide',()=>persist());
window.addEventListener('keydown',e=>{if(e.code==='Escape'&&!$('#about').classList.contains('hidden'))$('#about-close').click();});
const mapExplorer=new MapExplorer({cache:cityCache,onChoose:async({cell,campaign,coordinate})=>{
  if(cell.prepared){setCampaign(null);const index=baseCatalog.findIndex(level=>level.id===cell.id);await selectLevel(index,{start:true,fromMap:true,entryPoint:coordinate});}
  else{setCampaign(campaign);const index=campaign.sectors.findIndex(s=>s.id===cell.id);await selectLevel(baseCatalog.length+index,{start:true,fromMap:true,entryPoint:coordinate});}
},onCancel:()=>cancelMapSelection(),onAdvanced:()=>openAdvanced(),onSettings:()=>{mapExplorer.hide();state='menu';showScreen('menu');renderLevels();$('#play').textContent=repo?'Продолжить игру ↗':'Выбрать район на карте ↗';$('#play').disabled=false;}});
const cityPicker=new CityPicker({cache:cityCache,client:osmClient,onChoose:activateCampaign,onClose:()=>openMap()});
async function openAdvanced(){await persist();mapExplorer.hide();state='city-picker';input.reset();showScreen(null);await cityPicker.open(activeCampaign);}
async function openMap(){const token=++generation;sectorLoader.cancel();state='map';input.reset();showScreen(null);await persist();if(token!==generation)return;repo?.dispose();repo=null;absorption.reset();animations=absorption.animations;renderer.dispose();const campaigns=await cityCache.campaigns().catch(()=>[]),preparedProgress={};for(const level of baseCatalog){const saved=await saves.getRun(level.id).catch(()=>null);if(saved)preparedProgress[level.id]={completed:saved.completed,consumedArea:saved.consumedArea,totalBuildingArea:level.totalBuildingArea};}if(token!==generation)return;await mapExplorer.open({catalog:baseCatalog,campaigns,preparedProgress});}
function cancelMapSelection(){generation++;sectorLoader.cancel();repo?.dispose();repo=null;renderer.dispose();state='map';input.reset();showScreen(null);mapExplorer.cancelSelection();}
$('#city-open').onclick=()=>openAdvanced();
$('#cancel-import').onclick=()=>sectorLoader.cancel();
async function showEmptySector(entry,emptyManifest,token=generation){const updated=await cityCache.updateProgress(emptyManifest.campaignId,entry.id,{completed:true,empty:true,totalBuildingArea:0,consumedArea:0,version:emptyManifest.version});if(token!==generation)return;activeCampaign=updated;run=null;manifest=emptyManifest;repo=null;state='result';showScreen('result');$('#hud').classList.add('hidden');$('#result-title').textContent='Здесь нет зданий.';$('#result-place').textContent=`${entry.title}: в OSM нет подходящих контуров внутри этого участка.`;$('#result-stats').innerHTML='<p>Участок проверен и отмечен пустым. Можно перейти к следующему.</p>';$('#record').textContent='Пустые участки не дают очков и не создают вымышленных объектов.';$('#replay').classList.add('hidden');updateNextButton();renderLevels();}
applySettings();state='map';showScreen(null);requestAnimationFrame(tick);
(async()=>{if(new URLSearchParams(location.search).has('test')&&new URLSearchParams(location.search).has('hud')){state='layout-preview';showScreen(null);document.body.dataset.state='playing';document.body.classList.add('has-progress');$('#hud').classList.remove('hidden');$('#game-bottom').classList.remove('hidden');$('#pause').classList.remove('hidden');$('#progress-value').textContent='0.04';$('#progress-fill').style.width='0.04%';$('#mobile-radius').textContent='21 м';$('#radius-value').innerHTML='21 <small>м</small>';$('#count-value').textContent='10';$('#score-value').textContent='209';$('#time-value').textContent='00:23';$('#hud-level').textContent='Пушкин';const note=document.createElement('div');note.id='layout-preview-warning';note.textContent='ПРЕДПРОСМОТР HUD · ИГРА НЕ ЗАПУЩЕНА';$('#app').append(note);return;}try{await saves.init();unlocked=await saves.unlocked();const data=await fetchJSON(new URL('./data/catalog.json',location.href));baseCatalog=data.levels;setCampaign(null);const lastLevel=await saves.lastLevel();try{const cities=await cityCache.campaigns(),previous=cities.find(c=>c.sectors.some(sector=>sector.id===lastLevel));if(previous)setCampaign(previous);}catch{}const lastIndex=catalog.findIndex(level=>level.id===lastLevel);levelIndex=lastIndex>=0?lastIndex:0;renderLevels();await openMap();}catch(error){console.error(error);toast('Данные города недоступны. Обнови страницу после проверки интернета.',true);$('#play').textContent='Обновить страницу';$('#play').disabled=false;$('#play').onclick=()=>location.reload();}})();
// Explicit query-gated diagnostics, useful for verifying real-data persistence and geometry.
if(new URLSearchParams(location.search).has('test')){window.__cityEater={snapshot:()=>({state,levelIndex,manifest,run:run?serializeRun(run):null,loadedIds:repo?[...repo.buildings.keys()]:[],chunks:repo?[...repo.chunks.keys()]:[],animations:animations.length}),get game(){return{run,repo,manifest,renderer};},pause,resume,persist,selectLevel,play,async moveTo(position){if(!run)return;run.position=position;await repo.update(position,run.radius);renderer.camera(position,run.radius,10);renderer.syncBuildings(repo);},async absorb(id){const b=repo.buildings.get(id);if(b&&consumeBuilding(run,b,manifest)){repo.consume(id);renderer.syncBuildings(repo);renderer.setRadius(run.radius);await persist();return true;}return false;}};$('#fps').classList.remove('hidden');}
if(new URLSearchParams(location.search).has('test')){
  const panel=document.createElement('details');panel.id='qa-panel';panel.className='panel';panel.innerHTML='<summary>QA controls</summary><small>Test mode changes this browser’s progress using real OSM IDs.</small><button data-qa="nearest">Nearest edible</button><button data-qa="stream">Stream away / back</button><button data-qa="save">Save checkpoint</button><button data-qa="goal">Reach goal (real IDs)</button><output id="qa-city-metrics">OSM requests: 0 | cached: 0 | imported: 0</output><pre id="qa-status">Ready</pre>';$('#app').append(panel);
  panel.addEventListener('click',async event=>{const action=event.target.dataset.qa;if(!action||!run||!repo)return;const button=event.target;button.disabled=true;const status=$('#qa-status');try{
    if(action==='nearest'){const b=[...repo.buildings.values()].filter(b=>b.radius<=run.radius*1.06).sort((a,b)=>Math.hypot(a.center[0]-run.position[0],a.center[1]-run.position[1])-Math.hypot(b.center[0]-run.position[0],b.center[1]-run.position[1]))[0];if(!b)throw new Error('No edible building loaded');await window.__cityEater.moveTo([...b.center]);if(state==='paused')resume();if(state==='menu')await play();status.textContent=`Target ${b.id}, ${b.area} m²`;}
    if(action==='stream'){const p=[...run.position],s=state;if(s==='playing')pause();await window.__cityEater.moveTo([-4200,-4200]);await window.__cityEater.moveTo(p);if(s==='playing')resume();status.textContent=`Streamed away/back. Consumed: ${run.consumed.size}. Loaded: ${repo.buildings.size}`;}
    if(action==='save'){await persist();status.textContent=JSON.stringify({level:run.levelId,consumed:run.consumed.size,area:run.consumedArea,score:run.score,radius:run.radius,version:run.version},null,2);}
    if(action==='goal'){if(state==='playing')pause();for(const chunk of manifest.chunks){const data=manifest.campaignId?await cityCache.loadChunk(manifest.id,chunk):await fetchJSON(new URL(chunk.url,repo.baseUrl));for(const b of data.buildings){consumeBuilding(run,b,manifest);repo.consume(b.id);if(run.completed)break;}status.textContent=`Real OSM IDs consumed: ${run.consumed.size}`;if(run.completed)break;}absorption.reset();animations=absorption.animations;renderer.setRadius(run.radius);renderer.syncBuildings(repo);await complete();status.textContent=`Goal ${progressPercent(run,manifest).toFixed(2)}%; ${run.consumed.size} real OSM buildings`;}
  }catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
}

document.addEventListener('keydown',event=>{if(event.key!=='Tab')return;const dialogs=[...document.querySelectorAll('.modal-screen:not(.hidden)')],dialog=dialogs.at(-1);if(!dialog)return;const focusable=[...dialog.querySelectorAll('button:not(:disabled),a[href],select,input,[tabindex=\"0\"]')].filter(el=>el.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(!dialog.contains(document.activeElement)){event.preventDefault();first.focus();}else if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
