import {STREAM_MODE,serializeStreamRun} from './streaming-state.js';
/** Separate DB: opening this preview never migrates or deletes old game saves. */
export class StreamStore {
  constructor(){this.db=null;this.opening=null;}
  async init(){if(this.db)return this;if(this.opening)return this.opening;this.opening=new Promise((resolve,reject)=>{const r=indexedDB.open('city-eater-stream-v1',1);r.onupgradeneeded=()=>{r.result.createObjectStore('runs',{keyPath:'sectorId'});const masks=r.result.createObjectStore('masks',{keyPath:'id'});masks.createIndex('sectorId','sectorId');};r.onsuccess=()=>{this.db=r.result;resolve(this);};r.onerror=()=>reject(r.error);});return this.opening;}
  async load(sectorId){await this.init();return new Promise((resolve,reject)=>{const t=this.db.transaction(['runs','masks'],'readonly'),run=t.objectStore('runs').get(sectorId),masks=t.objectStore('masks').index('sectorId').getAll(sectorId);t.oncomplete=()=>resolve({run:run.result??null,masks:(masks.result||[]).map(item=>({key:item.key,bits:item.bits}))});t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
  async progress(){await this.init();return new Promise((resolve,reject)=>{const t=this.db.transaction('runs','readonly'),r=t.objectStore('runs').getAll();t.oncomplete=()=>resolve(r.result||[]);t.onerror=()=>reject(t.error);});}
  async save(run,chunks){if(run.mode!==STREAM_MODE)throw new Error('Неверный формат сохранения.');const snapshot=serializeStreamRun(run),records=[...chunks].map(([key,bits])=>[key,new Uint8Array(bits)]);await this.init();return new Promise((resolve,reject)=>{const t=this.db.transaction(['runs','masks'],'readwrite');t.objectStore('runs').put(snapshot);for(const [key,bits] of records)t.objectStore('masks').put({id:`${snapshot.sectorId}::${key}`,sectorId:snapshot.sectorId,key,bits});t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
  async reset(sectorId){await this.init();return new Promise((resolve,reject)=>{const t=this.db.transaction(['runs','masks'],'readwrite');t.objectStore('runs').delete(sectorId);const r=t.objectStore('masks').index('sectorId').openKeyCursor(sectorId);r.onsuccess=()=>{const c=r.result;if(c){t.objectStore('masks').delete(c.primaryKey);c.continue();}};t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}
}
